### ISSUE TITLE
Tests per day

### ISSUE THREAD

**Issue by ptalvistu** [koroonakaart/koroonakaart#106]
The mouseover for tests per day chart includes positive, negative and percentage numbers, but the percentage (however rounded) is also given with positive and negative numbers. Wouldn't it be better to just discard the percentage line and show the unrounded number with positive and negative. Even if you don't discard it, the % symbol appears twice in the percentage line so one should be removed.

**Comment by neuroactive** [comment]
Thanks for the feedback. I've made some improvements to the tooltips and this is fixed now.

![tests-tooltip](https://user-images.githubusercontent.com/22959023/116590313-436cfe80-a926-11eb-954b-d202a55c6f27.png)
