### ISSUE TITLE
Rolling average instead of or in addition to daily cases/deaths cumulated

### ISSUE THREAD

**Issue by mrlnmartinson** [koroonakaart/koroonakaart#109]
This eliminates the false sense of precision we get from looking at daily numbers / cumulative cases or deaths and provides a way more reliable overview of the real trends. 

_See [John Burn Murdoch's work for FT](https://twitter.com/jburnmurdoch/status/1250178043001405441) for reference_

**Comment by neuroactive** [comment]
This is a valid point, but as adding a trendline to the chart of daily cases has already been suggested in #92, I am closing this issue in favour of that one.
