### ISSUE TITLE
Show % of gender stats

### ISSUE THREAD

**Issue by analytik** [koroonakaart/koroonakaart#115]
What worries me is the gender disparity. I don't have a solid explanation for it, but women are getting tested about 2x more than men. The last time I manually counted this, 3 weeks ago, I had numbers like:
```
1709 men tested negative
2611 women tested negative

187 men tested positive
215 women tested positive

7.6% of women tested positive
9.86% of men tested positive
49% more women being tested
33% fewer men are getting tested
```

I would like to see the percentage and totals per gender, as would make this gender disparity more visible.

Also if anyone has an explanation for this, hit me up please. So far I attributed it to toxic masculinity more than anything.

**Comment by Abercus** [comment]
Hi!

My own thought on this is that a lot of the difference can attributed to two factors:
1) front-line workers (nurses, doctors) are tested more. In 2017, 96.6% of nurses were female and 74% of doctors were female;
2) proportional differences in sex in the Estonian population, especially in the elderly group.

Joonas

**Comment by PuuraJ** [comment]
Hi!

My own thought on this is that a lot of the difference can largely be attributed to two factors:

1) front-line workers (nurses, doctors) are tested more. In 2017, 96.6% of nurses were female and 74% of doctors were female;
2) sex differences in Estonian population, especially in the elderly group.

**Comment by keeganmcbride** [comment]
I will try to implement a chart for this, there are still many things to do, but I have fallen behind due to other work needing to be done.

**Comment by keeganmcbride** [comment]
https://www.koroonakaart.ee/et/chart?chart=GenderChart&height=400&width=400

**Comment by keeganmcbride** [comment]
Should be done now, let me know if this is okay.

**Comment by analytik** [comment]
Looks great, thanks!
