### ISSUE TITLE
Better visual indication of direction in summary numbers

### ISSUE THREAD

**Issue by jaanus** [koroonakaart/koroonakaart#118]
Noticed that recently, small numbers about change have been added to the top summary numbers. For example "Confirmed cases: 1592 ( +33 )". This is a great change because it quickly shows you the change without having to study the graphs further below.

To further ease the reading of the change, it could be augmented with direction arrow and color. Here’s a very quick and dirty mockup of what I mean.

![arrow and color](https://user-images.githubusercontent.com/184253/80188770-53b71300-861a-11ea-8bb3-f0bf33a03cad.png)

I guess the color could have grades depending on the magnitude of change. There seems to be some color coding on the rest of the page (e.g darkness of blue color for “confirmed cases per country” on the map), the colors of the change indicators could match the colors on the rest of the page.

**Comment by keeganmcbride** [comment]
@Kypsis

**Comment by Kypsis** [comment]
Added the code for the color change. Not quite sure if the the arrows add or subtract from the UX seeing as we already have the + and - sign. **Confirmed cases**, **Deaths**, **Discharged from hospital** and **Tests administered** can only increase while **In treatment** is the only one that can decrease to negative. The arrows might leave the wrong impression.

There is a case for the arrows representing if current days change is greater or lesser than  the previous days data but again from UX standpoint would have to implement tooltip or other means to relay what the ever changing arrow denotes.

Currently the KISS principle might the best approach in this case.
