### ISSUE TITLE
Compare number of tests to confirmed cases

### ISSUE THREAD

**Issue by neuroactive** [koroonakaart/koroonakaart#12]
Issue migrated from neuroactive/koroonakaart:

aomaesalu commented 2 days ago
Currently, the number of tests and the number of confirmed cases are displayed on separate charts. That is great for clarity. However, from March 12 onwards, these numbers already seem to be heavily correlated. This indicates that the number of tests could be a bottleneck. Therefore, it would be interesting to have some way to compare these two values over time.

**Comment by neuroactive** [comment]
Right, we displayed those on separate charts in the interest of clarity. We will bear in mind your suggestion to make it possible to compare those values.

We are exploring what other data we could present in relation to the tests. We feel it would be useful, for example, to add data about how many tests are being done by region. However, whether this is possible depends entirely on whether the relevant authorities will be prepared to release such data to us.

**Comment by maert-aab** [comment]
I would appreciate such chart as illustrated in linked spreadsheet - % of positive cases from tests done. 
https://docs.google.com/spreadsheets/d/1uq6XwK-LavPUyoPB4qWFkFXEemRlfSFnkLLKMD5Hgw0/edit?usp=sharing

**Comment by semirenko** [comment]
Such a chart is definitely needed to see the trend of confirmed cases.

**Comment by tarmo888** [comment]
Something like this https://www.facebook.com/photo.php?fbid=10158195628459521&set=a.76088949520&type=3&theater

**Comment by keeganmcbride** [comment]
![teste-pevas](https://user-images.githubusercontent.com/20890951/77623286-805b0a80-6f48-11ea-8b76-6458ccd6fd9a.png)
Added in https://github.com/okestonia/koroonakaart/commit/c0fbd6df525135ee4880d2249d05d94b5fce0235

**Comment by kaljuvee** [comment]
Thanks looks cool, thanks for the quick turnaround!

I guess minor cosmetic enhancement would be to get the English legends on the English version but this is great already :)

**Comment by keeganmcbride** [comment]
![tests-per-day](https://user-images.githubusercontent.com/20890951/77639247-20249280-6f61-11ea-8646-a190e644f44e.png)
It should be there already?

**Comment by kaljuvee** [comment]
ok didn't show up for me before but looks good now, some browser cashing issue. Cheers!
