### ISSUE TITLE
Positives vs people ill with corona

### ISSUE THREAD

**Issue by TiiuS** [koroonakaart/koroonakaart#122]
Current stats list everyone with positive test result as ill which cannot be the case. Could we have them separated?
Also - could we have comparative demographic charts with the ones presented now? I.e. we see that 2700+ cases are confirmed for age group females 45-49 and 2670 cases for females age group 85+, but there has to be a difference in how many people we have in these brackets nationwise.

**Comment by neuroactive** [comment]
Thanks for your suggestions.

Many of the statistics on the site relate to positive test results, which means that there is a high probability that the relevant people are infected with the Sars-Cov-2 virus. We don't say anywhere that all those who have a positive test result are "ill". It is, however, highly unlikely that we would be able to get data on how many people have symptoms as opposed to being asymptomatic due primarily to difficulties in data collection. Bear in mind that not all those who have a positive test will be seen by a doctor. There is therefore no realistic way for us to get the data you are asking for.

I have noted your point about wanting to see the statistics about cases by different age groups shown in relation to the number of people overall in those age groups. I am going to merge this issue into #113 as it is effectively the same.
