### ISSUE TITLE
Suggestion: remove "Active cases estimate" data

### ISSUE THREAD

**Issue by eeyou** [koroonakaart/koroonakaart#125]
As the subject says, suggesting removal of "Active cases estimate" data and related to it graphs.

Considering that:
- We only have confirmed cases, that come from tests and not everyone is being tested
- We have no numbers of actual recoveries, but simply discharged from hospitals (I assume, such people still may be infected, but simply need no hospital care anymore and can finish recovering at home in self-isolation)
- In general even total confirmed cases number is relatively small value - just 0.12% from total population of Estonia
- There's seemingly no explanation of how "Active cases estimate" numbers are calculated

It may lead some people to feeling, that it's totally safe to ignore all kinds of restrictions put by the government.

**Comment by eeyou** [comment]
Alternatively make it so, that this data is shown in opt-in manner - some switch to display estimated data + some fair warning, that this is just estimation (and how estimated).
Also, it might be a good idea to add somewhere in the website something like "please, follow recommendations from the government and the restrictions put by it".

**Comment by kaheksa** [comment]
The "Active cases estimate" follows the guidelines from terviseamet. If you have no symptoms after 2 weeks you are cured. Something like this is needed to show how the virus is evolving in the comunity. Just everyday new confirmed cases doesnt show anything. After a month we might have 2000 confirmed, but nobody is actually sick anymore...

**Comment by 1postituvi** [comment]
In this case, this guideline has poor value when trying to estimate the current status. Since according to available preliminary data, the median time from onset to clinical recovery is 2 weeks for mild cases and 3-6 weeks for patients with severe or critical disease, then I would suggest that it could be safely said that all people who were tested positive 6 weeks ago (and have not died), have recovered.
