### ISSUE TITLE
Track number of cases for 14-day period

### ISSUE THREAD

**Issue by jaanus** [koroonakaart/koroonakaart#129]
I cannot immediately find/remember the source for it, but I remember from the news that there seems to be a standard emerging to track the cases: number of (new?/ongoing?) cases per 100K people over past 14 day period. This would be the basis for recommending tightening/relaxing measures by the authorities.

We should of course find the source and confirm that the above is true. But if so, it would be a useful new variable to represent.

**Comment by keeganmcbride** [comment]
They talked about the european recommendation of 50 per 100k but Estonia wanted less like 25 or something. ECDC should have more info. Sent while walking

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by jaanus** [comment]
Right. Here is one source: https://www.ecdc.europa.eu/en/current-risk-assessment-novel-coronavirus-situation where it says:

> 19 countries reporting a current 14-day incidence below 50 cases per 100 000 population

So if I read it correctly, it is simply the number of new cases for past 14 days per 100K population, tracked over time.

**Comment by keeganmcbride** [comment]
Yes that is correct. You can take the active case estimate number and that is all tests in last 14 days that are positive roughly

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by analytik** [comment]
In general, being able to shorten the date range would be useful, especially since data becomes harder to see in comparison with the first wave. For example if I select total cases only in Harjumaa, new infections in the past 2 weeks seem almost flat, even if it's 20 new cases. I assume this would be a lot of work, but then again, we're probably going to deal with this for another year or more.

**Comment by rinne** [comment]
I think new cases over 14 previous days (i.e. current + 13 previous) would be most relevant for entire population and could simply be added as additional value in "New cases per day" histogram.  It would also be more or less trivial to calculate that over historical data.

**Comment by keeganmcbride** [comment]
Yes, I can add this in to the Statsbar I suppose, but really it is just the "Active Cases Estimate" divided by 12 or 13 (not sure the official pop numbers atm).

**Comment by keeganmcbride** [comment]
Seems to be like 13.4, but if someone finds the official number I can do it.

**Comment by keeganmcbride** [comment]
and a quick version is up live now.
