### ISSUE TITLE
Kuupäeva filter

### ISSUE THREAD

**Issue by sander2009** [koroonakaart/koroonakaart#131]
Selleks, et paremini aru saada nt eriolukorra järgneva perioodi trendidest, lisada filter, mis võimaldaks filtreerida välja andmeid (ja kuvada andmeid) valitud perioodi kohta.

**Comment by urmaskaa** [comment]
Võiks lisada 14 päeva nupu(hinnangulise nakatunute arvu metoodikast tingitud)
28 päeva nupu(terviseameti poolt leiutatud päevade arv, millega nad eeldavad, et vaikus haigusloos tähendab tervenemist)
Lisaks on highchartil olemas selline asi nagu zoom, et selle võiks ka lubada, et saaks ise vahemikku hiirega valida

**Comment by keeganmcbride** [comment]
@Kypsis has played with this a bit, but the functionality on mobile is quite bad. We will think about how to proceed / best tackle this issue, especially as the time series becomes increasingly large.

**Comment by keeganmcbride** [comment]
Added in an initial version of this, will keep working on it a bit this week.
