### ISSUE TITLE
Map filters aren't applied to "sub-maps"

### ISSUE THREAD

**Issue by Madis0** [koroonakaart/koroonakaart#139]
Reproduce: 
1. Filter the map as "active cases estimate" 
2. Click on a region, e.g. Harjumaa 
3. Filters reset to "absolute count"

Also the filters section is not visible at all in sub-maps and the back button is titled "Tagasi" regardless of selected language.

**Comment by keeganmcbride** [comment]
Yes, this is a known bug, will try to fix it, but currently development resources are very limited as this project is volunteer run. Will add it to the do-list, but no promises as to when it will be fixed.

**Comment by keeganmcbride** [comment]
@muhammednagy If you feel up for it, this would be a big help for you to tackle.

**Comment by muhammednagy** [comment]
Hey sure feel free to assign it to me.

**Comment by keeganmcbride** [comment]
This should be fixed now we just disabled where maptype != absolute.

**Comment by Madis0** [comment]
Now I don't see any sub-maps at all, clicking does nothing...

**Comment by keeganmcbride** [comment]
This was disabled when we first put added ik the playback feature, must have forgotten to reenable, will fix.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by keeganmcbride** [comment]
@Madis0  If you go to the absolute count map, then the municipality levels graphs will work. There is no other municipality level graphs other than for this data due to the nature of the statistics provided (e.g. only given a range).

**Comment by Madis0** [comment]
Oh, okay. I thought the absolute count was given and others were calculated by you.

**Comment by keeganmcbride** [comment]
We take the data from opendata.digilugu.ee you can check it out and see what we have access to, if you have an idea on how to better visualize smthin just let us know.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
