### ISSUE TITLE
Show statistics on map relative to population

### ISSUE THREAD

**Issue by neuroactive** [koroonakaart/koroonakaart#14]
Issue migrated from neuroactive/koroonakaart:

aomaesalu commented 2 days ago
Currently, the heatmap seems to be based on absolute values. However, as over 40% of the population lives in Harju county, that is going to define the map. Having a heatmap with values relative to the population of the corresponding counties could improve the overview of the spread of the virus. You could have a toggle to switch whether to use absolute or relative values, so the page would not get too convoluted with different charts.

neuroactive commented 2 days ago
Thanks for the feedback. That's a reasonable point, and we are looking to improve the options for how the graph is presented. We are somewhat limited by time and resources at present.

zidik commented 2 days ago • 
Using the number of cases relative to number of inhabitants would really make sense for the heatmap; It would give a better sense of prevalence of the virus in the region.

But could this be skewed by the availability of the testing in each region? Would number of cases relative to people tested would make more sense?

aomaesalu commented 2 days ago
Yes, I agree with @zidik. However, is there information on the number of tests by county?

neuroactive commented 2 days ago
We are planning to make it possible to present the map using cases by number of inhabitants.

Unfortunately, county-level information about tests hasn't been made available to us yet.

**Comment by neuroactive** [comment]
The current provisional plan is to make it possible to browse any of the headline statistics (Confirmed cases, Active cases, etc) relative to the population in each county. However, traffic to the app is increasing fast, so first we need to spend some time improving the infrastructure before we tackle additional features.

**Comment by peeterplaaster** [comment]
Even if the county to population info is hard to get, the "tests to population" and "infected to population" would be a really good help.

**Comment by keeganmcbride** [comment]
We have added a graph showing total positive tests per 10,000 population now. Soon we hope to add this option to the map as well.

**Comment by keeganmcbride** [comment]
This has been implemented and once local changes are pushed it will be live.
