### ISSUE TITLE
create a graph with 14-day cumulative number of new cases per 100 000

### ISSUE THREAD

**Issue by ansun789** [koroonakaart/koroonakaart#143]
I suggest to create a graph showing the evolution of the 14-day cumulative number of COVID-19 cases per 100 000 data, and also it's distribution per different counties (e.g 14-day cumulative number of COVID-19 cases per 100 000 in Harjumaa, Ida-virumaa, etc.). This will help to compare to the scale and understand the evolution trends. thank you

**Comment by keeganmcbride** [comment]
Will think about doing this, but I am not sure if / when I will have time to implement. If someone else wants to take the initiative, it would be appreciated.

**Comment by Eskumu** [comment]
I played around with data scripts and I have the numbers, but I'm not sure if we should create new graph for this data or should we add these statistics to "Haigusjuhud" chart? 

![image](https://user-images.githubusercontent.com/21247241/92321917-a4159700-f036-11ea-8fcd-965e1305c442.png)

I'm thinking that these numbers are relatively small compared to other numbers in this graph, making 100k stats hard to see alongside other statistics in this graph.
![image](https://user-images.githubusercontent.com/21247241/92321969-138b8680-f037-11ea-8b0a-1262a45cf1f0.png)

**Comment by keeganmcbride** [comment]
Thanks! I think it perhaps makes sense to create a new chart as haigusjuhud is already quite full. As a side note, I think tehik releases time series data for the 14 day incidence per 100k as open data.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by keeganmcbride** [comment]
If you make a pr I can take a look in like an hour or so and then get it up live.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by Eskumu** [comment]
Sorry, but I got Rally to watch :checkered_flag: 

But I'll try to take a look in the evening.

**Comment by keeganmcbride** [comment]
resolved by @Eskumu.
