### ISSUE TITLE
Add a LICENSE

### ISSUE THREAD

**Issue by lacabra** [koroonakaart/koroonakaart#152]
Dear project maintainers,

Thank you 🙏for open sourcing this project, this is great! 🙌

In order for many others to use this project, they need to know under which terms they can do so, and that's where including a LICENSE in your repo is immensely helpful, as it can actually make all the difference in whether they can use or not depending on what license do you release this project under.

Could you please include and specify a license for this project?
If you need any guidance, see https://choosealicense.com/, or acknowledging that is mostly a data project, consider a [Creative Commons license](https://creativecommons.org/licenses/)

Thanks again 🙏
Victor

**Comment by keeganmcbride** [comment]
Hi @lacabra thanks for reaching out about the licensing issue, it is something we are currently working on. Naturally we want it to be as open as possible, but as we use Highcharts it sort of complicates the licensing process as they release it for OS projects under CC BY NC. Any advice from you on licensing would be appreciated as we also debate this internally.

**Comment by lacabra** [comment]
Hi @keeganmcbride, thanks for giving me the opportunity to weigh in. Unfortunately, you are in a very tricky position here because Highcharts has done something quite tricky to begin with. By limiting the commercial use of their software downstream, they don't comply with neither [the definition of open source software](https://opensource.org/osd) from the OSI nor [the free software definition](https://en.wikipedia.org/wiki/Free_software) from [FSF](https://www.fsf.org/). So just to be clear, even though Highcharts makes their source code available, Highcharts is neither open source software nor free/libre software. 

It is obvious that they were fully aware of this limitation because they couldn't find a proper open source license to release their software; so they had to look elsewhere. They landed on a Creative Commons license, despite the explicit  [recommendation that should not be applied to software](https://creativecommons.org/faq/#can-i-apply-a-creative-commons-license-to-software), arguing that CC licenses *do not contain specific terms about the distribution of source code, which is often important to ensuring the free reuse and modifiability of software*. So interestingly, it seems that Highcharts landed on a sort of a *legal void* because they are releasing source code under a license that is meant for content, and thus the term **Works** does not explicitly cover source code. How did this happen? Probably because instead of paying the hefty fees of a lawyer firm to craft a license for their specific needs, they looked for the cheap alternative in open source and open content, but there is really nothing that covers what they want here... hence this mess.

Of course these statements come with the disclaimer that I am not a lawyer, and nothing of this is legal advice: I do not recommend to disregard their CC-BY-NC license solely on the basis that it does not seem to apply to source code.

So, what do you do? It seems that you have essentially two alternatives:

* Keep propagating this mess downstream and license your product under the very same license that Highcharts use. If you proceed this route, kindly put a BIG disclaimer around your license to properly communicate this to your user base from the onset, so that they know what they are getting into. Arguably this makes your product less attractive, and it is plausible that you overlooked the license terms when you initially chose Highcharts as a dependency; so you have an opportunity to provide clear information about the consequences of this choice to your users as you wish you had properly considered this when you made your choice.

* Realizing the consequences of having Highcharts as a dependency, you may want to reconsider your dependency on Highcharts altogether, and replace it with a *proper* open source software library, which would allow to license your product properly with a permissive license, and give back to the open source community.

Maybe you choose the first option short term, and work towards the second option on a longer timeline.

Side note: I am the technical lead for the [Digital Public Goods Alliance](https://digitalpublicgoods.net) working off the [UNICEF Office of Innovation](https://unicef.org/innovation). I came across your project looking to nominate it as a Digital Public Good: https://github.com/unicef/publicgoods-candidates as it seems to align with the advancement of the Sustainable Development Goals. However, this licensing issue does not make it eligible as software, which brings up another thought:

Since this repo contains both **data** and **software**, and both components can be clearly separated, I strongly urge you to differentiate between the two, and include an appropriate license for each component. Refer to the [recommended licenses for Digital Public Goods](https://github.com/unicef/publicgoods-candidates/blob/master/docs/licenses.md) for open content, open data and open source software. We could thus nominate the data component as a Digital Public Good now, and add the software component if/when you replace Highcharts.

Happy to continue the discussion as needed.

**Comment by keeganmcbride** [comment]
Hi @lacabra thanks for the detailed and well thought out response! It is much appreciated. I will discuss with @infokujur from Open Knowledge Estonia as well as the rest of the dev team (@PuuraJ  @Kypsis) about our next steps. Perhaps though, you and I could also discuss over a quick call / email? You can get me at mcbride@hertie-school.org

**Comment by lacabra** [comment]
Hi @keeganmcbride, yes I would be happy to discuss over a call. I've emailed you with some suggested times.

**Comment by keeganmcbride** [comment]
A temporary solution has been found and is now included in the readme.

**Comment by lacabra** [comment]
👆 changes introduced in 90d69d75d651648ea0be60ccb22484a55b741549

And further changes proposed in #155
