### ISSUE TITLE
"Tests made" diagram won't allow total percentage diagram switch

### ISSUE THREAD

**Issue by jgkarl** [koroonakaart/koroonakaart#158]
Within "Tests made" diagram, it is not possible to switch to 'total percentage' view, upper right corner. 'Absolute' is default view.

**Comment by keeganmcbride** [comment]
Thanks! Will take a look and see what has happened there.

**Comment by keeganmcbride** [comment]
Fixed it yesterday, sorry forgot to write it earlier.
