### ISSUE TITLE
Improve mobile functionality

### ISSUE THREAD

**Issue by neuroactive** [koroonakaart/koroonakaart#16]
keeganmcbride commented 2 days ago
Right now mobile functionality is not so good, it should be improved .

**Comment by neuroactive** [comment]
I've made some changes to improve the responsiveness of the design. The main remaining obstacle in getting the site to work better on mobiles is the fixed width map. This would be solved by replacing it with a responsive map.

**Comment by arva-zz** [comment]
Scrolling with mobile is PITA as the graphs are zoomable and instead of scrolling it tends to zoom the graphs. I don't think that zoomable graphs offer any value on mobile. Static graph is more usable and I even think that rendered image would be good idea on mobile view

**Comment by neuroactive** [comment]
Thanks, that's a good point. Using a static graph instead is something we have considered. I will discuss this tomorrow with the other developers.

**Comment by keeganmcbride** [comment]
Half asleep I tried something, didn't work, but plotly has staticPlot: true as an option. So, it shouldn't be so hard to rig something up to enable if device != desktop.

**Comment by keeganmcbride** [comment]
This should be done now.
