### ISSUE TITLE
Using 2019 county population data when 2020 data is available

### ISSUE THREAD

**Issue by robtinkers** [koroonakaart/koroonakaart#175]
[`constants.py`](https://github.com/okestonia/koroonakaart/blob/master/TEHIK_Open_Data_Loading_Scripts/constants.py)  seems to be using the 2019 population data (e.g. Harjumaa 598.059) when [stat.ee](https://www.stat.ee/et/avasta-statistikat/piirkonnad) has 2020 data available (e.g. Harjumaa 605.029)

There is also a typo in [`main.py`](https://github.com/okestonia/koroonakaart/blob/master/TEHIK_Open_Data_Loading_Scripts/main.py) referring to `API_ENDPONT` rather than `API_ENDPO**I**NT`.

**Comment by neuroactive** [comment]
Thanks. I've updated the population figures for the counties and fixed the typo.
