### ISSUE TITLE
graafikute uuendamise probleem

### ISSUE THREAD

**Issue by terehommikust** [koroonakaart/koroonakaart#179]
Tere,

Palun uuendada ka graafikut "Surmad vanuserühma ja soo järgi", sest see on mõnes mõttes kõige olulisem info - selle järgi saab teada, milline ühiskonna grupp vajab kõige rohkem kaitset.

Teiseks, see koroonasse surnud alla 50 aastane naine oli väär-info - palun korrigeerige see ka ära. Sellel teemal oli mitmeid artikleid, näiteks see: https://leht.postimees.ee/7113997/46-aastane-narvalanna-ei-surnud-covid-19-tottu

Tänan.

**Comment by dorkster100** [comment]
Tere,

Hetkel meie räägime terviseametiga, et nemad avalikustaksid seda infot läbi mingisugust API. Hetkel oleme sunnitud saama infot selle graafiku jaoks uudistest.

Kahjuks kõik andmed ei ole läbi selle kanali saadaval.

**Comment by neuroactive** [comment]
@terehommikust You queried the cause of death for the individual under 50 who died. We are sourcing our data on deaths from Terviseamet press releases. They have access to much more detailed information regarding the cause of death than we do, so we need to go along with their assessments, even if there are press reports to the contrary. In cases where people die from Covid, it's relatively common that there are other conditions involved, which is perhaps why there is some confusion in this case. So we plan to leave the data as it is for the time being.

The chart for deaths by age and gender has been updated and is correct as at 3 December.

**Comment by terehommikust** [comment]
Tere taas,

Parast 3. detsembrit ei olegi vist "Surmad vanuserühma ja soo järgi" graafikut uuendatud. Milles on probleem? 

Olen kursis, et info uuendamisega tegelevad vabatahtlikud (ei saa küll aru miks!) aga sellegi poolest võiks asja korrektselt teha. 

Võiksite panna sinna juurde info, et kuna viimati uuendatud.

**Comment by dorkster100** [comment]
Tere,

Antud veebilehe haldab mitte riiklik organisatsioon ja tööd tehakse vabast ajast.

Mis puudutab vanuse ja soo graafikusse, hetkel käib läbirääkimine terviseametiga, et nad neid andmeid väljastaksid korrektselt, kui läbirääkimised ei õnnestu, siis tõenäoliselt meie kustutame antud graafiku veebilehelt ära. Probleem on selles, et hetkel neid andmeid saab ainult läbi uudiste kanali ja kahjuks ei ole kõikide surmade kohta infot.

**Comment by terehommikust** [comment]
Tänan vastuse eest.

Soovin tähelepanu juhtida paarile asjaolule:

- Koroona on teemaks alates märtsi kuust ja praegu võiks info vahetamine juba korrektselt toimida.
- Graafiku kustutamine pole vastuvõetav, sest kodanikel on õigus infole mis puudutab koroona surmadega seotud statistikat!

Mina isiklikult ei poolda sellise lehekülje haldamist vabatahtlike poolt, sest siis on justkui "OK" kui kõik päris korras ei ole ja keegi ei vastuta...

**Comment by dorkster100** [comment]
Vabatahtlike poolt haldamine, on eesotsas seotud sellega, et antud projekti rahastamine on puudulik ja toimub läbi toetuste, mida jällegi inimesed vabatahtlikult kannavad organisatsioonile, mis selle veebilehe haldamisega tegeleb. See info on avalik ja on lehel olemas.

Kui teil on soovi aidata, siis võite a) võta projektist osa b) aidata toetustega.

> Graafiku kustutamine pole vastuvõetav, sest kodanikel on õigus infole mis puudutab koroona surmadega seotud statistikat!

Olen teiega nõus, ja arvan igaüks kes selle projektiga tegeleb on teiega samat meelt, kuid kahjuks hetkel riik ei avalda seda infot täies mahus. Kui olukord ei muutu, siis hoida üleval graafikut, mille info ei ole 100% õige on pigem halb. Vähemalt selline on minu vaatenurk.

> Koroona on teemaks alates märtsi kuust ja praegu võiks info vahetamine juba korrektselt toimida.

Kuna meie ei ole riiklik organisatsioon ja ei ole kuidagi nendega seotud, siis meie kasutame andmete näitamiseks avaliku infot, mida igaüks saab kasutada. Kahjuks riigi poolt on andmete avaldamisega mõned probleemid ja puudused, eriti mis on seotud surmadega, surmade arv on avaldatud ainult kodulehel ja uudistes ja surnud inimeste vanus ja sugu on avaldatud ainult uudistes ja mitte täies mahus. Oleme samuti nagu teie kurva meelt selle üle.

**Comment by neuroactive** [comment]
Closing this as a duplicate of #127.
