### ISSUE TITLE
Data from the future in the New Cases Per Day plot

### ISSUE THREAD

**Issue by ottojolanki** [koroonakaart/koroonakaart#192]
Hello, 
and thank you for this awesome service. 
Today when I opened the english version of the page, I noticed that the default data range in New Cases Per Day plot is Feb26 2020 to Feb27 2021, with data from future dates showing non zero number of discharged from hospital. Perhaps some dates are handled as mere numbers instead of `datetime`s?

**Comment by dorkster100** [comment]
Hello,

Thank you for your report, the issue should be fixed now.

If there are any further issues, please let us know, otherwise feel free to close the issue.
