### ISSUE TITLE
Add vaccinations data

### ISSUE THREAD

**Issue by martinl** [koroonakaart/koroonakaart#193]
Hi,

thank you for maintaining this informative resource. Please also add vaccinations data available at opendata.digilugu.ee to Koroonakaart, eg something similar to www.err.ee chart:
<img width="433" alt="Screenshot 2021-01-10 at 12 57 01" src="https://user-images.githubusercontent.com/148686/104121233-5e9b0a80-5345-11eb-8de1-b74b4a4306c0.png">

with best regards,
Martin

**Comment by dorkster100** [comment]
I will try to do that, however currently i sadly do not have enough time to do that in the nearest future. Will do when i have some available time.

Anyone is welcome to submit PR though.
