### ISSUE TITLE
What happened to deaths by age?

### ISSUE THREAD

**Issue by lbho** [koroonakaart/koroonakaart#194]
This chart is no longer visible on the website - I'd noticed it hadn't been updated in a bit, but is there a reason it was removed?

**Comment by dorkster100** [comment]
Chart was removed due to data not being available. It was only partially being made available through news. So having chart up with false data does more harm than good.

We tried speaking with terviseamet regarding this issue, but there was no result.

**Comment by lbho** [comment]
That's a real shame. I'd been watching that number for months as the best gauge for "when will people start realizing this is a serious issue and behave accordingly?"  But if they don't let us know when we start losing under-50s, well. 

Thanks for the update, I appreciate your work.
