### ISSUE TITLE
Make map responsive

### ISSUE THREAD

**Issue by neuroactive** [koroonakaart/koroonakaart#20]
The map should resize depending on the dimensions of the browser window. There is a good example of a responsive D3 map here (with tooltips):

https://bl.ocks.org/jpasini/dca25b76efe015ef42433c5ca019e27b

It may be possible to fix the responsiveness of the map with some adjustments to the existing code. Alternatively, we could implement a responsive map using a different library.

**Comment by keeganmcbride** [comment]
Should be done now.
