### ISSUE TITLE
Error in labelling / calculation of vaccinated people

### ISSUE THREAD

**Issue by taivop** [koroonakaart/koroonakaart#205]
There seems to be an inconsistency in shown number of vaccinated people.

At time of writing (29 Jan evening) Terviseamet is [reporting](https://www.terviseamet.ee/et/koroonaviirus/koroonakaart)
* 34019 _doses administered_, including
  * 26412 people who've had 1 *or* 2 shots
  * 7607 people who've had 2 shots

Koroonakaart, however is reporting the same numbers with different interpretations:
* 34019 "all vaccinated" which would lead me to believe it is the number of people -- which it isn't
  * 26412 people who've had 1 shot (excl 2-shot people)
  * 7607 people who've had 2 shots
  
The fix should be easy - either relabelling the graph or calculating the true number of 1-shot-excl-2-shots people as 26412 - 7607 = 18805.

**Comment by dorkster100** [comment]
Hello,
Thank you for your remark. I am not able to fix this immediately, but will on Tuesday.

**Comment by Rainerkikkas** [comment]
Hi, I haven't fully checked the pull request, but seems there might still be a logic flaw in the vaccination number calculation/interpretation still.
As of today (2021-02-07), Terviseamet reports (https://www.terviseamet.ee/et/uudised/covid-19-blogi-7-veebruar-oopaevaga-lisandus-417-positiivset-testi) that a total of 35 905 people have received a vaccination shot, out of which 17 519 people have received 2 shots. My understanding is that the total number includes both those who have had 1 shot, as well as those who have had 2 shots.
But the graph on koroonakaart.ee is adding those 2 numbers up to show the total number of people who have received either 1 or 2 shots:
![image](https://user-images.githubusercontent.com/54767647/107142883-7fea1900-693a-11eb-9700-68d7a63ac46b.png)
If the purpose of the blue line is to show the total number of shots that were administered, then the label has to be changed. At the moment, the label is talking about number of people, not number of shots

**Comment by neuroactive** [comment]
@Rainerkikkas I believe the pull request addresses the problem you mentioned. My understanding is that the blue line aims to show the total number of people who have received either one or two shots. The label for that line should probably be made clearer.

A stacked bar chart might be a better way to present this data as that would show more clearly how the proportion of those who have had one and two shots contributes to the total.

**Comment by neuroactive** [comment]
@sarnane Many thanks for the pull request. This has now been merged and the correct figures are now showing on the site.

I still think some improvements could be made to the labels and presentation of the vaccination data, but I will open a separate issue to discuss those.
