### ISSUE TITLE
Aktiivsete haigusjuhtude hinnang maakonniti

### ISSUE THREAD

**Issue by maag58** [koroonakaart/koroonakaart#207]
Something seems to be wrong with this presentation.
The total number of active cases is given in the top paragraph about 7000,
whereas sum by counties gives something 6-fold.

**Comment by neuroactive** [comment]
I don't see any mistake. The number of active cases by county shown on the map is consistent with the total number of active cases shown in the figures at the top of the page.

The "Haigusjuhud maakonniti" section below the map shows the cumulative number of confirmed cases in each county, not the current estimate of active cases. Perhaps that is the source of the confusion.

**Comment by maag58** [comment]
![akt_maak](https://user-images.githubusercontent.com/62912841/106883640-ee379d00-66e8-11eb-97bc-ab9ce260001f.jpg)

**Comment by maag58** [comment]
Aa, now I see - "Aktiivsete haigusjuhtude hinnang" is not title, it is a choice.
Then it is ok, sorry for disturbing.

**Comment by neuroactive** [comment]
No problem. We will try to make things clearer when we review the design of the charts.
