### ISSUE TITLE
Intensiivravis/juhitaval hingamisel olevate patsientide aegrida

### ISSUE THREAD

**Issue by Almondovar** [koroonakaart/koroonakaart#209]
Kas saaks näidata intensiivravis ja juhitaval hingamisel olevate haigete arvu ajas graafikuna? Aitaks hinnata tõsiselt haigete patsientide muutust ajas. 
Aitäh!
AV

**Comment by tarmo888** [comment]
Hetkel paistab, et intensiivravil näidatakse hoopis juhitaval hingamisel olevate arvu ja päriselt intensiivravil olevate infot ei näidata üldse.
https://github.com/okestonia/koroonakaart/blob/ad38a0ac68ecae96c2e0d38473c0381a465836f1/TEHIK_Open_Data_Loading_Scripts/main.py#L118
https://github.com/okestonia/koroonakaart/blob/ad38a0ac68ecae96c2e0d38473c0381a465836f1/TEHIK_Open_Data_Loading_Scripts/chart_data_functions.py#L528

**Comment by neuroactive** [comment]
@tarmo888 Thanks, we are aware of this issue and will fix it as soon as we find time to do so.

**Comment by neuroactive** [comment]
> Kas saaks näidata intensiivravis ja juhitaval hingamisel olevate haigete arvu ajas graafikuna? Aitaks hinnata tõsiselt haigete patsientide muutust ajas.

@Almondovar We plan to review the charts presented on the site before long and will consider adding separate charts for both the number of people in intensive care and those on ventilation.

For now, a chart showing the number of people on ventilation can be seen by isolating the "Intensiivravil" line in the "Haigusjuhud" chart.

![ventilation](https://user-images.githubusercontent.com/22959023/109984410-699e6580-7d0c-11eb-8182-fbc26b3467ce.png)

**Comment by Almondovar** [comment]
@neuroactive Great, thank you! I think that these data characterize most objectively the spread of the infection as these are not dependent on the testing criteria (presence of symptoms, travel, screening activity) and testing activity.

**Comment by bmiis** [comment]
Is it possible to show the "Cases" and "New cases per day" data on the same chat. Especially like to see together "Intensive care"-"On ventilation"-"Deaths(daily)" and "In treatment"-"Discharged from hospital(daily)"-"Confirmed cases(daily)". These show the negative and positive flow dynamic in hospitals. The overall cases summaries are not comparable with hospital current patient counts.
Aitäh!
