### ISSUE TITLE
[Ekiri] Haiglaravil olevate patsientide arv

### ISSUE THREAD

**Issue by infokujur** [koroonakaart/koroonakaart#221]
Ekirja sisu:

Koroonakaart.ee lehel on viimastel nädalatel haiglaravil patsientide arv suurem kui ERR-i avaldatud uudistes. Näiteks täna ütleb ERR, et haiglaravil on 727 inimest, koroonakaart.ee ütleb 736. Intensiivravil ja juhitaval hingamisel patsientide arv on sama olnud. Kas andmed pärinevad erinevatest allikatest ja on erinevalt arvutatud või on mingi viga? Varem olid numbrid ühesugused.

**Comment by neuroactive** [comment]
I believe the issue here is that there are two separate statistics regarding hospitalisation, which are calculated in slightly different ways. My understanding is that one includes patients who are being treated in hospital during the day but who don't stay overnight, whereas the other does not.

**Comment by neuroactive** [comment]
I think it would be helpful if we added explanations of the different statistics alongside the relevant parts of the website. Then we could put the detailed information about exactly what each statistic represents there. I will start a separate issue for that.

**Comment by neuroactive** [comment]
Am going to close this issue now as I don't believe the hospitalisation data we are showing on the site is wrong. If any evidence is provided that it is in fact wrong, we can reopen the issue.
