### ISSUE TITLE
"All vaccinated from eligible population" bad translation?

### ISSUE THREAD

**Issue by paanda86** [koroonakaart/koroonakaart#222]
This looks like it is calculated from total population not **eligible** population.

Either this could be calculated with ineligible age groups removed, or the name could be changed.

The Estonian is different:
Elanikkonnast kõik vaktsineeritud = Population vaccinated

**Comment by neuroactive** [comment]
Thanks. Yes, that is certainly inconsistent with the Estonian translation and may not be correct. I will try to find out how that statistic is being calculated to check.

There are some other improvements to the translations that need to be made, partly as some of the definitions have changed to take into account the new one-shot vaccines. My proposed changes are as follows:

All vaccinated -> Total vaccinated (including partially)
Partially vaccinated (1 shot) -> Partially vaccinated
Completely vaccinated (2 shots) -> Fully vaccinated
Completely vaccinated from all vaccinated -> Fully vaccinated out of total vaccinated

I will fix these today.

If someone could supply an Estonian or Russian translation of the following term, that would be helpful:

Total vaccinated (including partially)

**Comment by paanda86** [comment]
I did the math and the statistic is definitely being calculated based on the full population of Estonia
236598/1328976=0.178

Kõik vaktsineeritud is technically fine for that I think (the stat has always been called this but includes both partial and completed vaccinations) its strongly implied that it includes partial vaccinations since there is also the completely vaccinated stat (Täielikult vaktsineeritud)

But if the distinction is important then: 
Kõik vaktsineeritud (osaliselt + täielikult)

**Comment by paanda86** [comment]
Personally I would prefer a stat which was truly **All vaccinated from eligible population** just as a tiny bit of good news 21.8% vs 17.8%

But I get why people might be against this (could be perceived as massaging the numbers)

**Comment by neuroactive** [comment]
Thanks. Just using the term "Vaccinated" is a bit problematic in my opinion as it's unclear what it means without looking at the other terms. Arguably it's even misleading as many of those who are counted in the "Vaccinated" statistic won't have developed immunity. So I would favour wording which makes it clear that it includes partially vaccinated people as well.

For stylistic reasons, I'd prefer to avoid a plus symbol in the text and think it would be better to make the translations as close to each other as reasonably possible. So I would propose we use the following text:

Kõik vaktsineeritud (sealhulgas osaliselt)

Does that look OK?

It would be impossible for us to accurately calculate how many people in the country are ineligible for vaccination as we won't be able to find out how many are excluded on medical grounds. So I guess we can leave the calculation of that as it is for now. The other point is that the age range for those eligible for vaccination may well change, so the statistic will be more stable if we simply calculate it as a percentage of the total population.

**Comment by paanda86** [comment]
Yep, makes sense.

Kõik vaktsineeritud (sealhulgas osaliselt) is good
