### ISSUE TITLE
Improve precision at which statistics are displayed

### ISSUE THREAD

**Issue by neuroactive** [koroonakaart/koroonakaart#224]
Many statistics are currently displayed to an inappropriate number of decimal places (mostly with too many decimal places, but some with an insufficient number). It would improve clarity to format these to a more appropriate level of precision.

We should modify the formatNumberByLocale() function so that it takes an optional argument of the number of decimal places to which a number should be formatted. The default precision should be zero decimal places.

I would propose changing the precision all of the following statistics to 1 decimal place:

14-day cumulative number of COVID-19 cases per 100,000 (and the daily change)
Average proportion of positive tests in the last 14 days
Total vaccinated out of entire population
Fully vaccinated out of total vaccinated
Positive tests per 10,000 population by county
Tests per day (positive and negative)
Positive and negative tests by county
Positive and negative tests by gender

**Comment by FottyM** [comment]
- [x] 14-day cumulative number of COVID-19 cases per 100,000 (and the daily change)
- [x] Average proportion of positive tests in the last 14 days
- [x] Total vaccinated out of the entire population
- [x] Fully vaccinated out of total vaccinated
- [x] Positive tests per 10,000 population by county
- [x] Tests per day (positive and negative)
- [x] Positive and negative tests by county
- [x] Positive and negative tests by gender

**Comment by neuroactive** [comment]
The numbers should be at the correct precision everywhere now, so I am closing this.
