### ISSUE TITLE
Casually suggesting non-generic scripts

### ISSUE THREAD

**Issue by lietu** [koroonakaart/koroonakaart#238]
Your README now casually suggests people run this `update_data.sh` -script. Script which has things like:

```bash
rm -rf ../../backup
mkdir ../../backup
cp -Ra ../../koroonakaart ../../backup
ln -srfn ../../backup/koroonakaart/koroonakaart/dist ../../current
```

You DO understand that these are NOT things you should randomly be running on other peoples' computers, right? You should not go about randomly deleting and creating folders from outside the checkout directory. If you have such scripts in the repo, you should specifically flag them as potentially dangerous for people who do not know what to do with them, NOT promote them in your README.

**Comment by neuroactive** [comment]
Thanks, that is a fair point. I've removed the script from the repo and it is no longer referenced in the README, so I am closing this issue.
