### ISSUE TITLE
Teste päevas/Tests per day broken for all zoom values except for initial "All"

### ISSUE THREAD

**Issue by nju001** [koroonakaart/koroonakaart#240]
If I click the Tests per day 3m button, I can only see the date associated with the graph bar, no values for the numbers of negative or positive tests when I mouse over the graph. In fact, I can only see these numbers in the initial "All" graph. Changing the zoom removes the possibility of viewing any numerical values.

**Comment by neuroactive** [comment]
OK, thanks. I am looking into it. I am seeing inconsistent results after changing the zoom. For some dates, I see the detailed figures in the tooltip, but for other dates the numbers are missing.

**Comment by neuroactive** [comment]
@nju001 This is now fixed. Do please raise another issue if you notice any other bugs.
