### ISSUE TITLE
More testing should be a good thing, not a bad thing

### ISSUE THREAD

**Issue by lietu** [koroonakaart/koroonakaart#246]
Right now when you have more tests done the number is shown as red, it should be green:

![image](https://user-images.githubusercontent.com/1296558/117551545-44510f00-b04f-11eb-8ef5-b921268f9cd4.png)

**Comment by neuroactive** [comment]
I have checked the site in two different browsers but I see increase in tests in green. Are you sure this issue isn't only in your fork?

![tests](https://user-images.githubusercontent.com/22959023/117552921-00fa9e80-b057-11eb-8245-a712018a7b2b.png)

**Comment by lietu** [comment]
Interesting, I thought I was actually looking at koroonakaart.ee when I saw that .. maybe it's my fork 😄
