### ISSUE TITLE
Ask legal if collecting personal information is OK - if person agrees.

### ISSUE THREAD

**Issue by infokujur** [koroonakaart/koroonakaart#26]

**Comment by whysthatso** [comment]
or get rid of tracking alltogether.

**Comment by keeganmcbride** [comment]
OUt of scope for now.

**Comment by whysthatso** [comment]
if so, shouldn't you then at least remove any tracker so as to at least conform to basic legal restrictions?

**Comment by keeganmcbride** [comment]
The issue here was that others wanted to post a form and ask people to fill out to collect data about what symptoms they had etc, sort of to try to build a crowdsourced map of corona spread in Estonia. We decided this was not in scope for our project.

**Comment by whysthatso** [comment]
fair enough, then i misunderstood the issue.
