### ISSUE TITLE
 Relative infection in different age groups

### ISSUE THREAD

**Issue by NosyMe** [koroonakaart/koroonakaart#29]
To give a realistic picture of the infection in different age groups, give the % of positive responses for the total number of tests performed in that age group.

**Comment by keeganmcbride** [comment]
This should be added now, we don't have data on positive / negative by age group, but we do have total positive by age group.

**Comment by lookingfordata** [comment]
Not having/displaying data for all cases tested by age group is a serious issue. Interpreting positive cases by age group without considering the total number of people tested in that age group can lead to seriously wrong conclusions. For example, if only people over 60 are tested, then 100% of positive cases are also over 60, which is meaningless! Please at least pass on this information to appropriate people, if you can.

**Comment by keeganmcbride** [comment]
I agree with you that this information is important, if Terviseamet releases it then we can make it available.

**Comment by keeganmcbride** [comment]
@lookingfordata I have added this info into the application now. I think the graph could use some work, but there is pos / neg by gender and by age.

**Comment by m6tlik** [comment]
Instead, more age-groups above 65+ should be added, (relative to age groups 0-4 etc)

**Comment by keeganmcbride** [comment]
The structures of the data comes from Terviseamet, we don't make the grouping so I can't show anything other than 65+. The original issue is addressed now though so will close the issue.
