### ISSUE TITLE
Review About text and publish that on koroonakaart.ee

### ISSUE THREAD

**Issue by infokujur** [koroonakaart/koroonakaart#3]
https://github.com/okestonia/koroonakaart/blob/master/README.md

**Comment by kunstnik** [comment]
Noticed recently:
En and Ru versions are running nicely on:
https://koroonakaart.ee/en, ... /ru
but not on the main page of Terviseamet/Health Dept. 
Language buttons on dark gray ribbon are black and not functioning, not existing in the intro pop-up window either.
2 
Got weird notices: Ligipääs keelatud & Sul puudub õigus antud lehte vaadata... , even though I saw everything...? Look at:
![sketch-1585316657534 png](https://user-images.githubusercontent.com/62639296/77762598-70bfec80-7042-11ea-921d-6e7fe4f927cc.jpg)

![sketch-1585316743407 png](https://user-images.githubusercontent.com/62639296/77762535-5980ff00-7042-11ea-9106-1f26a8d265f5.jpg)

**Comment by kunstnik** [comment]
3
Have you decided to shear our data to worldometer?
https://www.worldometers.info/report_us/

**Comment by keeganmcbride** [comment]
This is coming now, so will close.
