### ISSUE TITLE
Open png in new tab

### ISSUE THREAD

**Issue by infokujur** [koroonakaart/koroonakaart#30]
"https://www.terviseamet.ee/et/koroonaviirus/koroonakaart
"Download plot as .png" - oleks hea kui saaks pildi avada uues tabis, paljud keskkonad aktsepteerivad copy-paste-i, siis ei peaks vahesammudega mässama."

Is that something what Terviseamet should do?

**Comment by keeganmcbride** [comment]
SHould be done now.

**Comment by aomaesalu** [comment]
Is it? I only see download options.
