### ISSUE TITLE
Haldusjaotusest ja versioonist

### ISSUE THREAD

**Issue by Andmeteadlane** [koroonakaart/koroonakaart#31]
![Haldus2005](https://user-images.githubusercontent.com/62432476/77169058-8de44080-6ac1-11ea-9ed6-e2abdd7d75a4.png)

Tere!

Nägin rakendust ja tahaks juhtida tähelepanu kasutatavale maakondlikule haldusjaotusele. Nimelt taoline jaotus oli pädev 2005. aastani, mil Lehtse valla territoorium (kaardil Järvamaa põhjaosa) liitus Lääne-Virumaaga ja ülejäänud maakonnad on haldusreformi eelsed...seega tekib küsimus, et kuidas on see siis versioon 20180901?

**Comment by keeganmcbride** [comment]
Good catch, when we migrated to the new app we switched to a new JSON, will update.

**Comment by keeganmcbride** [comment]
https://code.highcharts.com/mapdata/countries/ee/ee-all.geo.json

**Comment by Andmeteadlane** [comment]
No problem, that was first thing what caught my eye, as previous version actually had the right administrative divison :)

**Comment by keeganmcbride** [comment]
Fixed now. Thanks again for raising this.
