### ISSUE TITLE
Idea: playback of corona-history

### ISSUE THREAD

**Issue by ToomasMolder** [koroonakaart/koroonakaart#35]
(just idea, probable label 'data / data visualisation')

Public / citizens / analysts might want to see playback of corona-history, visualized. From where it started (Saaremaa), how it spread (Võrumaa, Harjumaa, etc), how it spread with different speed in different counties (growth of number of 'Kinnitatud haigusjuhud maakonniti'), etc.

Starting from the first day when case found (2020-02-26) and playing until current day, sample changing / refreshing map with colors, speed one second / day (sample). Or by allowing viewer to slide date pointer between date axis.

**Comment by keeganmcbride** [comment]
I like this idea, I talked with @Kypsis  and @PuuraJ  and it is pretty simple to set up. I will try to add it in the coming days.

**Comment by keeganmcbride** [comment]
We are in progress of making this happen now.

**Comment by keeganmcbride** [comment]
This has been added to live now.
