### ISSUE TITLE
Wrong data "Insufficient data" in some graphs

### ISSUE THREAD

**Issue by dreambuilder123** [koroonakaart/koroonakaart#36]
"Insufficient data" should be "Harjumaa" in the following two graphs.
<img width="630" alt="Screen Shot 2020-03-22 at 11 18 08 PM" src="https://user-images.githubusercontent.com/34392488/77260961-b459d580-6c93-11ea-92d4-f9816a05285e.png">
<img width="451" alt="Screen Shot 2020-03-22 at 11 16 53 PM" src="https://user-images.githubusercontent.com/34392488/77260884-4dd4b780-6c93-11ea-9403-c0881a47fcbc.png">

Don't know "Insufficient data" means what here because there are already 15 counties. Better put the names alphabetically like others.
<img width="533" alt="Screen Shot 2020-03-22 at 11 18 32 PM" src="https://user-images.githubusercontent.com/34392488/77260988-dbb0a280-6c93-11ea-83ad-010485c94585.png">

**Comment by keeganmcbride** [comment]
Hi, thanks for pointing this out. I just pushed the fix for the insufficient data bug. Re the 3rd graph, Insufficient data means they have no entry for these people in the rahvastiku (population) register and therefore they are unknown location.

________________________________

**Comment by dreambuilder123** [comment]
Hi, thank you for your prompt response! 
About the 3rd, do you mean "Info puudulik" like you used in other graphs? Actually I prefer the one word **"unknown"** like you used in **Distribution of positive tests by age** :)

**Comment by keeganmcbride** [comment]
Data he been reordered.
