### ISSUE TITLE
Language issue

### ISSUE THREAD

**Issue by dreambuilder123** [koroonakaart/koroonakaart#37]
It would be nice if these texts could be translated for the English and Russian versions. 
Thanks a lot! :)
<img width="893" alt="Screen Shot 2020-03-22 at 11 47 23 PM" src="https://user-images.githubusercontent.com/34392488/77261520-adcd5d00-6c97-11ea-9a0e-e0bd0da96dc3.png">
<img width="542" alt="Screen Shot 2020-03-22 at 11 47 52 PM" src="https://user-images.githubusercontent.com/34392488/77261518-ac039980-6c97-11ea-8ba4-153c24c3c880.png">

**Comment by keeganmcbride** [comment]
@Kypsis  is working on this now.
