### ISSUE TITLE
“New cases per day” chart stacking?

### ISSUE THREAD

**Issue by joellimberg** [koroonakaart/koroonakaart#38]
It seems that the “New cases per day” chart is using a stacked bar chart, making the bars as high as "cases" **+** "recovered".

For example, March 22 has 20 cases, but the bar is higher than 20.

<img width="529" alt="Screen Shot 2020-03-23 at 10 52 45" src="https://user-images.githubusercontent.com/875872/77299090-a4bea900-6cf4-11ea-9bc9-d65ce1ab78f7.png">

<img width="222" alt="Screen Shot 2020-03-23 at 10 52 50" src="https://user-images.githubusercontent.com/875872/77299151-b86a0f80-6cf4-11ea-94bf-252828ad3723.png">

**Comment by keeganmcbride** [comment]
Thanks, will fix.

**Comment by keeganmcbride** [comment]
60955444b095b9326e865ae0b390dc3f53668eba
