### ISSUE TITLE
Daily number of hospitalized/in serious condition

### ISSUE THREAD

**Issue by eststat** [koroonakaart/koroonakaart#39]
It would be useful to present daily number of hospitalized patients and daily number of patients in serious/critical condition over time. This information seems to be available, but at the moment only current numbers of a given day are presented (time-series is not presented).

This information could be added to the 'Kumulatiivsed haigusjuhud' plot. This would help to visualize how fast cases turn into hospitalizations or to serious/critical. This would also give a rough idea of the percentage of active cases that are hospitalized/in critical situation at every time point.

**Comment by veikod** [comment]
Also, it would be useful if you add a trend line for daily number of hospitalized patients.

**Comment by keeganmcbride** [comment]
We have now added haiglaravil to haigusjuhud graph.
