### ISSUE TITLE
Distribution map within a county

### ISSUE THREAD

**Issue by m6tlik** [koroonakaart/koroonakaart#43]
In most highly infected counties (Harju), more detailed distribution map (municipalities) could be produced to pinpoint on infection hot-spots for locals to be aware.

**Comment by keeganmcbride** [comment]
Right now this data is not available from terviseamet, if it becomes so in the future we will add it. I will close the issue for now.

**Comment by m6tlik** [comment]
Could you make a request also from the developers side to Terviseamet, and
I try to push them from local public side. Probably they just do not have trust in abilities to present that.
But Finish case of closing on small region shows its value.
J

________________________________________
Saatja: keeganmcbride <notifications@github.com>
Saadetud: teisipäev, 24. märts 2020 22:39
Adressaat: okestonia/koroonakaart
Koopia: Jaan Liira; Author
Teema: Re: [okestonia/koroonakaart] Distribution map within a county (#43)

Right now this data is not available from terviseamet, if it becomes so in the future we will add it. I will close the issue for now.
