### ISSUE TITLE
Raw data feed/sheet

### ISSUE THREAD

**Issue by paanda86** [koroonakaart/koroonakaart#47]
Would it be possible to publish the data in an RSS feed or a public google sheet

**Comment by keeganmcbride** [comment]
We use this in our app: https://github.com/okestonia/koroonakaart/blob/master/koroonakaart/src/data.json

but there is a crowdsourced version here also: https://docs.google.com/spreadsheets/d/1nGRqoWD6B8zXqBE7ftW2DG5sX9HNTu5FMoehBygLdg0/edit#gid=0
