### ISSUE TITLE
Time to heal

### ISSUE THREAD

**Issue by olavilaitala** [koroonakaart/koroonakaart#48]
Is it possible to deduce the time to heal from the data?

**Comment by Q-lds** [comment]
I don't think information about individuals is provided. However you can have cumulative graphs of deceased and recovered like the one in the picture (for italy)

![image](https://user-images.githubusercontent.com/35239244/77515534-5a1e6780-6e81-11ea-93c7-6b5481d0d144.png)

**Comment by keeganmcbride** [comment]
We won't have this information, so I will close the issue as it won't be possible to implement.
