### ISSUE TITLE
Full data download option

### ISSUE THREAD

**Issue by Kalamajakas** [koroonakaart/koroonakaart#50]
Could you please add a functionality to download either the full dataset.
Thanks in advance,

Peeter

**Comment by keeganmcbride** [comment]
full data is available at https://github.com/okestonia/koroonakaart/blob/master/koroonakaart/src/data.json

data added daily to https://opendata.riik.ee/andmehulgad/andmed-koroonaviiruse-hetkeolukorra-kohta/

And you can download data from charts by clicking on the hamburger menu in the top right corner for each chart in CSV, XLSX and/or view as data table.

**Comment by Kalamajakas** [comment]
Super. Thanks :)
