### ISSUE TITLE
Lisa 'positive rate' voi suhteline nakatunute hulk

### ISSUE THREAD

**Issue by kaljuvee** [koroonakaart/koroonakaart#53]
Soovitust oleks lisada normaliseeritud uued juhtumid mis naitaks seda et kui testimise arv laheb yles, siis protsentuaalselt kandjate osakaal on vahenendud

![image](https://user-images.githubusercontent.com/539240/77560497-3cbfbc80-6ec6-11ea-9e90-2da30329367b.png)
[estonia-corona.xlsx](https://github.com/okestonia/koroonakaart/files/4382124/estonia-corona.xlsx)

**Comment by semirenko** [comment]
duplicate of #12
