### ISSUE TITLE
Suggestion: add information regarding repeat tests

### ISSUE THREAD

**Issue by kuldkollane** [koroonakaart/koroonakaart#54]
If the information is available, it would be interesting to see how many tests are carried out for people who had previously tested negative. Front-line healthcare workers likely need to be tested repeatedly, for example, and the data could offer some assurance to the public that people do get re-tested if there is a need for it. Perhaps using two colors or two columns in the tests per day chart - so it would be possible to distinguish between 1st tests (esmakordsed) and repeat tests (kordustestid) per day?

**Comment by keeganmcbride** [comment]
This data is not available and therefore we won't be able to implement it. If Terviseamet provides this information we will revisit this.
