### ISSUE TITLE
Suggestion: Create embeddable link for graphs and tables

### ISSUE THREAD

**Issue by argokasper** [koroonakaart/koroonakaart#56]
Nice to have, as long as it's okay with all the legal rights.

**Comment by keeganmcbride** [comment]
We are working on adding this now. Highcharts has a free license only for open source projects, so I assume as long as there is no ads etc on the page it should be okay, but I am not a lawyer and will need to check this out.

**Comment by keeganmcbride** [comment]
This is done now. Anyone can click on the chart menu, and then "embed graph", for ex:


<iframe src="https://www.koroonakaart.ee/en/chart?chart=Map&height=400&width=400" scrolling="no" frameborder="0" style="overflow:hidden; height:400px; width:400px;" allowTransparency="true" loading="lazy"></iframe>
