### ISSUE TITLE
Too thin bars for "new cases per day" chart

### ISSUE THREAD

**Issue by TonisOrmisson** [koroonakaart/koroonakaart#57]
The bars for chart "new cases per day" are too thin. 

I would suggest bar overlapping at least 50% and less space between dates. 
Unfortunately I lack the suitable dev env for this set-up. 

but something like that:
[http://jsfiddle.net/qk82fnbs/1/](http://jsfiddle.net/qk82fnbs/1/)

```
    plotOptions: {
        column: {
        		pointWidth: 15,
            pointPadding: -0.2,
            borderWidth: 0
        }
    },
```

**Comment by keeganmcbride** [comment]
Updated.
