### ISSUE TITLE
suggestion:  make data representative using symptom classifications

### ISSUE THREAD

**Issue by jaak-kivi** [koroonakaart/koroonakaart#60]
Tracking positive test % is not representative due to there being a symptom threshold for taking a test, which also changes with the availability of tests. Hence, the % of one day can't be compared with that of another.

If possible, this could be solved by including into aggregated data the count of each primary symptom for tests and the count of those in risk groups. This would allow data normalisation and also has less time lag than simply tracking hospitalisations/intensive care numbers.

**Comment by kunstnik** [comment]
Please scroll down a bit at the issue #24

**Comment by keeganmcbride** [comment]
We don't have this data and I don't think it will be made available, for now it is not possible to complete this. If something changes, will reopen the issue.
