### ISSUE TITLE
To add major towns (population above 10 000 or 30 000) to the heatmap?

### ISSUE THREAD

**Issue by kunstnik** [koroonakaart/koroonakaart#61]
IF data is available...
As population density is an additional epidemic risk, as we see in New York, Madrid, Helsinki etc., wouldn't be reasonable to add to the Corona map of Estonia the capital city and major towns as:
Tallinn
Tartu
Narva
Pärnu
Kohtla-Järve
__________ (above 30 000)
Viljandi
Rakvere
Maardu
Sillamäe
Kuressaare
Valga
Võru
Jõhvi
__________ (above 10 000) ??

This could provide a clear view, if or when to close the borders between towns and rural areas or administrative units (like Finland did in Uusimaa county).
Of course, the number of cases in surrounding suburb area should be divided from the total number of county. So suburbs start to show probably a far lower number of cases and density, than the initial city area.
The mean population density varies from 1328 in cities to 11 per km² in rural area (2017), specifically  2676 in Tallinn city and Hiiumaa county 9 persons per km² ~over 200 times, which apparently is a significant difference in terms of virus spread probability. (Harjumaa 134, Tartumaa 49/km², also 2017, source: http://andmebaas.stat.ee/Index.aspx?lang=et&DataSetCode=Rv0291). Compare: NYC MSA 2274/km², New York State 159/km²  (2017, source: https://en.wikipedia.org/wiki/New_York_%28state%29?wprov=sfla1 ).
The corona cases density value could be an additional pop-up data on the map, as proposed in issue #23

If data is not available yet, to add only contours or spots of towns.

**Comment by keeganmcbride** [comment]
If we get more data then we will be able to increase the specificity of the map, at the moment I think we will leave it as it is.

**Comment by kunstnik** [comment]
Of course. Thanks.
