### ISSUE TITLE
Show (positive cases/tests conducted in the age group) of men and women

### ISSUE THREAD

**Issue by veikod** [koroonakaart/koroonakaart#62]
It would be helpful to show how many were tested positive in their respective age and sex groups compared to the tests conducted. I hypothesize that women are conducting more tests, therefore their numbers are close to the positive cases of men. Men, as usual in Estonian society, suffer silently, therefore the sex distribution in our data does not resemble the sex distribution in other countries. Maybe the sort of testing effectiveness measure (positive cases/tests conducted in the age group) would help to visualize that.

**Comment by keeganmcbride** [comment]
This should be there already as second to last graph

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by veikod** [comment]
That graph shows absolute numbers. I think, probability difference or percentage of positive tests in age and sex group should give an extra viewpoint.

**Comment by keeganmcbride** [comment]
Okay, yes, we had the percentage there initially but changed the graph. We are still working on making it nicer. Will see what I am able to do.

**Comment by kuldkollane** [comment]
Just to address one point in the initial request and perhaps add context: Estonia is a bit of an outlier (at least among OECD countries) in the sense that around 73-74% of our doctors are women. Medical personnel is more likely to be in contact with covid-19-positive population **and** they are tested regularly. This currently seems to be the main reason for the disparity over here. The OECD average is around 46% and in Italy, for example, it is 40%. I'm not sure if it's possible to get data regarding the amount of tests that were performed specifically for healthcare personnel or whether this information would be of public interest?

**Comment by veikod** [comment]
Now the sex distribution has gone. A mistake or a deliberate one?

**Comment by keeganmcbride** [comment]
Terviseamet has stopped sharing the gender data with us so we are only able to display the pos / neg by age atm and not by gender as well, unfortunately.

**Comment by keeganmcbride** [comment]
I will close this for now, the graph is there, if data comes back from Terviseamet it will be added back in.
