### ISSUE TITLE
Default to browser locale

### ISSUE THREAD

**Issue by andres-k** [koroonakaart/koroonakaart#63]
It might be polite to default to users browser locale, instead of  'ee'

https://github.com/kazupon/vue-i18n/issues/220

**Comment by muhammednagy** [comment]
i could do this one.
Will do it tonight.

**Comment by keeganmcbride** [comment]
If you want to take it on @muhammednagy  would be nice.

**Comment by muhammednagy** [comment]
Done @keeganmcbride

**Comment by Kypsis** [comment]
Had to remove this feature sadly because it created issues for the media and other external sites. Replaced with a simple cookie to remember users language choice.
