### ISSUE TITLE
Maakondade nimede näitamine mobiilis

### ISSUE THREAD

**Issue by Anni-M** [koroonakaart/koroonakaart#66]
![F51F0481-11FC-401D-A5F0-89F4AE11594D](https://user-images.githubusercontent.com/61053130/77815650-4105f880-70c5-11ea-819b-6824cef795b8.png)
Mobiilis näitab maakondasid üle ühe. Kuigi peale vajutades on nimi näha.
Super töö. Jõudu ja jaksu!

**Comment by Kypsis** [comment]
Fixed. Minimum device resolution width where all the labels will still show is now 369px. For example iPhone 6 and upwards.
