### ISSUE TITLE
Vanuseline jaotus

### ISSUE THREAD

**Issue by kadrip** [koroonakaart/koroonakaart#67]
Vanuse järgi on 65+ liiga suur vahemik, 65- ja 89-aastane ei tohiks samas jaotuses olla.

**Comment by kunstnik** [comment]
Agree, it would be fair to continue till 100. 64_69, 70_75...
For a teenager, everyone over 25 is already a fossil. 😊
I'm 61 - fortunately still on the map.

**Comment by keeganmcbride** [comment]
This is added now. It depended on data from Terviseamet, which they released today.
