### ISSUE TITLE
Get more detailed data from government

### ISSUE THREAD

**Issue by metsjeesus** [koroonakaart/koroonakaart#7]
Found a site https://korona.kans.io/
They got a nice idea what info is demanded.

**Comment by metsjeesus** [comment]
https://korona.kans.io/
is getting infro from
https://w3qa5ydb4l.execute-api.eu-west-1.amazonaws.com/prod/finnishCoronaData
I guess its manually created. Is there a api what is managed from estonian government?

**Comment by keeganmcbride** [comment]
ATM everything comes from Terviseamet press releases, we hope to improve this soon.
