### ISSUE TITLE
Speedometer 

### ISSUE THREAD

**Issue by kunstnik** [koroonakaart/koroonakaart#73]
Measuring the doubling speed of Covid-19. 
Discussed in the issue #34, a reverse speedometer concept is shown. 
Suggestion: to create an intuitive (traditional) speedometer, showing doubling speed today. 
Further on, to create a pair or a row of speedometers, marking pressing weather brake or gas pedal today and the speeds tomorrow, day over tomorrow and after a week, over two weeks (showing also deaths) and month showing slowing down the spread.

**Comment by keeganmcbride** [comment]
We are not planning on implementing this at this time, I don't see a way we can make it visually fit with the current application. In any case, we have decided not to implement any sort of forecasting on the application, which puts this out of scope.

**Comment by kunstnik** [comment]
Understood, thanks for reviewing.
