### ISSUE TITLE
Triggering events, search for them

### ISSUE THREAD

**Issue by kunstnik** [koroonakaart/koroonakaart#74]
To be able to give feedback, we should hardly try to find triggering events.
Speeding up and slowing down one's.
Discussed in the issue #70, giving an example: HS:n datadeski. 
There is no doubt, volleyball match was a speeding triggering event. The response was immediate and inevitable (as participants were unprotected), done by virus. But it was also partly invisible in our charts (not all contaminated persons were tested). 
Nevertheless peaks in charts show some regularity (at least in early stages, where there is one triggering event, not several at the same time). This obviousness disappeares by time as spread routes with different incubation times mix with each other (spread starts to be local). 
In slowing triggering events we have a longer delay: incubation time+testing+input to the statistics+decision making by authorities+announcement+response time by public(depends on local culture). A far more dimmed correlation. 
I feel, at this point we should start to work together with true epidemiologits and epidemic statisticians (as mentioned in my comment to issue #24 - 3 days ago). 
I'd assume, search for triggering events would be more productive and better localized than predicting amount of contaminated persons/"possible cases" (#24).

**Comment by keeganmcbride** [comment]
This is not within scope of the application, so will have to close the issue.

**Comment by kunstnik** [comment]
Thanks,... 
But, what is the scope of the Koroonakaart application?
Is it written anywhere here? 
Did I miss something?
