### ISSUE TITLE
"Tervenenud" counter title change

### ISSUE THREAD

**Issue by veikod** [koroonakaart/koroonakaart#77]
"Tervenenud" counter is misleading, as https://www.terviseamet.ee/et/uuskoroonaviirus shows that it is about people who were released from hospitals but not overall counter of those who got well. Or maybe is Terviseamet information misleading...

**Comment by keeganmcbride** [comment]
Will discuss with the team, we also had same thoughts, but Terviseamet sort of seems to use the same interchangeably...

**Comment by keeganmcbride** [comment]
Terviseamet changed their wording to make it clear that it is not recovered, but rather just released from the hospital. We have updated our application to reflect this change and also removed active cases for the time being as it is not clear how many patients have recovered, in the sense that they have no symptoms or have given a negative test.
