### ISSUE TITLE
With highest priority please add graph for different age groups

### ISSUE THREAD

**Issue by savespain-covid19** [koroonakaart/koroonakaart#78]
There is significantly faster spread in the age group 65+ that has gone hidden for some time. It means higher rate of hospitalizations. We need to catch these things fast.

**Comment by keeganmcbride** [comment]
![distribution-of-tests-by](https://user-images.githubusercontent.com/20890951/78022162-26e64780-735d-11ea-84d5-ecff100de730.png)
Isn't this there already though?

**Comment by savespain-covid19** [comment]
I see what went wrong. I did not add "historical". May bad.

You could not see a trend from this kind of graph. It is kind of important to catch something going bad in one age group as it happened in the 65+ age group. Something similar to the county progress graph. 

Is it more clear now?

**Comment by savespain-covid19** [comment]
![image](https://user-images.githubusercontent.com/62103428/78148833-96c80100-7435-11ea-9ae3-9063e53cc748.png)

22nd and 26th are interpolated.

**Comment by savespain-covid19** [comment]
![image](https://user-images.githubusercontent.com/62103428/78149243-0dfd9500-7436-11ea-892d-9d49d73ff8ec.png)

Perhaps the graph above would have given an early warning.
