### ISSUE TITLE
suggestion: counties numbers should be also harmonised on the basis of tests done

### ISSUE THREAD

**Issue by hallkass** [koroonakaart/koroonakaart#79]
Tests per capita differ a lot in some counties. Saaremaa has 4 times more tests per capita than Harjumaa and many counties have done 2 times less tests per capita than Harjumaa. That increases positive tests per 10 thousand people to much higher level than it should be.

So maybe county graphs should have also view where cases are are harmonised on the basis of tests done per capita somehow.

Regards

hk

**Comment by keeganmcbride** [comment]
We already do this for total cases, so it is quite straight forward to do on a per county basis as well, there are a few things ahead of this, but I will keep it in mind and try to implement soon.

**Comment by keeganmcbride** [comment]
Can you share a link or example of what you would like this to look like?

**Comment by bmiis** [comment]
Can you add an backward light gray item "Amount of capita" per county and second y-axis for them.
Also remove (%) from head, as can choose _Abs_.

**Comment by hallkass** [comment]
hi,

I would imagine graph like this:


Table name: positive cases per county
X – Day
Y – % of positive tests on that day
Lines – Counties 

It would show trend of new positives as percentage for every county and will put numbers of new cases in every county in context.

**Comment by neuroactive** [comment]
This seems very similar to #41, so I am merging this issue with that one.
