### ISSUE TITLE
Suggestion:  Active cases by counties

### ISSUE THREAD

**Issue by unkish** [koroonakaart/koroonakaart#80]
In addition to observing **Confirmed** cases by counties it would be nice to see statistics about **active** cases per county (and why not other data from Cases graph if possible).

Or does Confirmed cases imply "active" ?

**Comment by keeganmcbride** [comment]
This is not possible at the moment, unfortunately. The data is not available. Active cases is Total cases - deaths - healed and we are unable to know which county the deaths / healed are from. Though I agree it would be useful information.
