### ISSUE TITLE
Switch "Tests per day" to stacked bar chart with "%" and "Abs" buttons

### ISSUE THREAD

**Issue by erik-heintare** [koroonakaart/koroonakaart#83]
Current chart Tests per day is not showing Positive test per day, only the percentage. The easy fix and making it similar like "Distribution of tests by age".

Also the line should represent smth over time like cumulative Positive tests %, if it's just for one day then bar is better, so it would resolve this issue also.

**Comment by keeganmcbride** [comment]
![teste-pevas (1)](https://user-images.githubusercontent.com/20890951/78234286-a2700200-74df-11ea-8e2a-ebd139ee4af1.png)
Isn't this graph what you're asking for? It is total pos tests per day with a line to show the pos % per day?

**Comment by erik-heintare** [comment]
No, I was thinking about converting the chart to this layout:

![Screenshot 2020-04-02 at 13 07 10](https://user-images.githubusercontent.com/11735168/78236615-e87a9500-74e2-11ea-9ce0-2d5cf6df664c.png)

Then both percentage and absolute numbers would be shown. Also, the line comment still applies.

**Comment by bmiis** [comment]
How it looks:
1. if you put positive tests bottom, negative top and use logaritmic scale.
2. if you use linear, but two different scale on both sides.

The same for Abs "+/- maakonniti".

**Comment by PuuraJ** [comment]
I feel like that there is a potential trade-off in the choice of representation here. What the line for %-positive currently allows is to easily see the positive test proportion and its change through time dimension. Using stacked graph requires you to hover over the bar to see the proportion. 

I agree, that line isn't the best choice here, but I'd like to preserve an easy way to see the proportion of positive tests as a main view. I see two simple ideas here: 1) Add a button for the switch between the two ideas - stacked chart vs line. 2) Is to break positive percentage view away into a separate plot.

**Comment by erik-heintare** [comment]
Maybe then stacked bar chart with % line? then all information is available in one look.

**Comment by keeganmcbride** [comment]
Should be done now, @PuuraJ made the changes. Letus know what you think @erik-heintare

**Comment by erik-heintare** [comment]
Looks already pretty good. I'd switch positive and negative values(postives to the bottom) in stacked chart so that positive results would be easier to compare.

**Comment by bmiis** [comment]
And _Log_ scale?
