### ISSUE TITLE
historic data of positive/negative results per county

### ISSUE THREAD

**Issue by hallkass** [koroonakaart/koroonakaart#85]
do yo have this data available? you should as you update this graph daily. 

if you have it, can you share it?

daily cumulative numbers would be enough.

mostly i wonder how would trends look like without saaremaa.

regards,
a

**Comment by keeganmcbride** [comment]
This can all be gathered from https://opendata.digilugu.ee/, we don't have this graph right now, but it's not so hard to run. If you know R you could do something like:

library(dplyr)
library(jsonlite)
tests <- jsonlite::fromJSON("https://opendata.digilugu.ee/opendata_covid19_test_results.json")
tests <- as.data.frame(tests)
GitHub <- tests %>% group_by(County,ResultValue,ResultTime) %>% count(.)


________________________________

**Comment by keeganmcbride** [comment]
We have a daily count by County as well on the site you could download csv or xlsx from there.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by hallkass** [comment]
thank you. opendata helped a lot
