### ISSUE TITLE
Cumulative vs daily - "Haigusjuhud" - distace vs speed ?

### ISSUE THREAD

**Issue by bmiis** [koroonakaart/koroonakaart#87]
On "Haigusjuhud" half of items are daily bases (1, 2, 4) and another half (3, 5, 6) are cumulative.
At least its good to inform about it. First one's fall back to zero, others down't.

PS.
From where you get "Haiglaravil" and "Intensiivravil" data? Don't see them in "Terviseamet avaandmed".

**Comment by keeganmcbride** [comment]
Hi, can you please try to explain again what you mean? I don't understand your question or point. 

For the "PS", this data comes from Terviseamet's press releases, unfortunately not available via TEHIK right now.

**Comment by bmiis** [comment]
If there will be more "Deaths" than "Intensive care", dose it means that there is lack of intensive care equipement? No. 
"Deaths" are sum of all earlier days but "Intensive care" is just amount of current day.

**Comment by bmiis** [comment]
Solution:
'* - kumulatiivne väärtus.
[Diagram]
Kinnitatud haigusjuhud* ; Tervenenud* ; Aktiivsed ; Surmad* ; Haiglaravil ; Intensiivravil

You need also another y-axis for them.

**Comment by bmiis** [comment]
I'll try to explain. If you drive with car there is display for two different type of value, that you **can't compare** each other. Odometer ie **distance** in miles or kilometers you had driven and speedometer ie your current **speed** in miles per hour. They both have historical data. If you use the same y-axis for both type, in first miles the speed value is visible, but if time lasts longer,  distance value grows up but speed value decreases compare to distance and gets harder and harder to visualize, it will be pressed near to x-axis. _"Confirmed cases", "Recovered"_ and _"Deaths"_ are like distance or **"Cases over all"** vs _"Active", "In treatment"_ and _"Intensive care"_ are like speed or **"Current day active cases"**.

**Comment by savespain-covid19** [comment]
Have you get all new hospitalizations? Can you share this data (just a csv file would be perfectly fine)?

**Comment by bmiis** [comment]
One more explanation: Look 2020.04.04, there are 17 _Intensive care_ cases. At the same time, are 15 cases of them _Deaths_?
Can you change _Active_, _In treatment_ and _Intensive care_ to bars like _New cases per day_ or stacked bar and keep others as lines.

PS. Why you take away _Active_, its first item that starts to fall.

**Comment by bmiis** [comment]
And I explain for myself, excuse me.

_Active_ is not like speed but time delayed distance between _Confirmed cases_ and _Recovered_ plus _Deaths_. The same is with _In treatment_ and _Intensive care_, but there are no line for _all treated_ and no line for all who got intensive care. 
There is just different behavior of these lines, at the end first ones grow up, the second ones fall down to zero.
My discussions with myself started, because I didn't see, are all the _deaths_ came from _intensive care_, or are there deaths outside intensive care or treatment and I tried to compare _deaths_ and _intensive care_. As I understand there is no such data available in TEHIK jet.

Issue closed, sorry about disturbing.
