### ISSUE TITLE
Add cases/tests breakdown by age-group / gender

### ISSUE THREAD

**Issue by neuroactive** [koroonakaart/koroonakaart#9]
Issue migrated from neuroactive/koroonakaart:

adlerpriit commented yesterday
Not sure the data is available, but would be good to see how the tests / cases distribute across different age groups and / or gender.

**Comment by Q-lds** [comment]
And it would be awesome if some indicators regarding the testing criteria could be added.

I am yet to understand if only symptomatic people over 60/65 are being tested, or if there is a larger number of younger people who's also being tested.

For example, the increase of +16 recorded on March 20th at noon contained only 3 cases which were above 60 years of age.

Also, it would be important to know how many of the 250 daily tests belong to health workers (and, possibly) track their status separately.

**Comment by keeganmcbride** [comment]
Graphs have now been added to show positive tests by age group.

**Comment by Q-lds** [comment]
@keeganmcbride 

Is it known whether `number of tests = number of people tested`, or whether the number of people tested is a fraction of the number of tests?

In many countries people are tested at least twice (if not many more times, as it happened with Korean drivein testing facilities). The reasoning is that if you test positive you are positive, but you are if negative you are tested more than once to avoid false negatives.

**Comment by keeganmcbride** [comment]
As far as I understand it is number of tests == number of people tested. AKA there shouldn't be duplicate / triplicate people in the numbers. I am not 100% sure though.

**Comment by Q-lds** [comment]
Maybe it should be confirmed with the health board? In all the press releases they always only give the number of tests performed, and the number of positive cases. I have never seen a reference to the total number of people tested.

Do you now who could verify this piece of information? Important metrics like the number of people found positive per number of tests are void of meaning if the `tests=people` equality does not hold.

**Comment by keeganmcbride** [comment]
I confirmed it with the health board. # of tests == # people.
