### ISSUE TITLE
Ida-Virumaa is missing from cumulative cases by county graph

### ISSUE THREAD

**Issue by pixelerch** [koroonakaart/koroonakaart#90]
It is visible in the legend below the graph, but when you start to look for it, you don't see it plotted. If you disable all the other counties and only leave on Ida-Virumaa, you will have an empty plot.

**Comment by pixelerch** [comment]
![image](https://user-images.githubusercontent.com/16979639/78348456-b6346a80-75aa-11ea-8bde-d6ed981812cb.png)

**Comment by keeganmcbride** [comment]
Investigating now, thanks for pointing it out.

**Comment by keeganmcbride** [comment]
Fixed the issue. Thanks again for bringing it to our attention.
