### ISSUE TITLE
 Deaths and intensive care patients by counties and age 

### ISSUE THREAD

**Issue by andra96** [koroonakaart/koroonakaart#93]
If its possible please show  deaths and intensive care patients by counties and age.
Also total number how many patients have been in intensive care (includes those who have already recovered or died).

**Comment by bmiis** [comment]
Hold in mind explanation about "distance and speed" #87. 
Intensive care _"new cases"_, _"daily recovered"_ and _"daily died"_ are like **speed**,
intensive care _"total cases"_ , _"total intensive care recovered"_ are like **distance**.

PS. Total intensive care recovered patients are cases that doctors need to analyze deeply.

**Comment by keeganmcbride** [comment]
We don't have this data available, but if it becomes available we will release it / make a visualization.

**Comment by neuroactive** [comment]
As this is related to #186, I am merging this issue into that one.
