### ISSUE TITLE
Not an issue, a question

### ISSUE THREAD

**Issue by savespain-covid19** [koroonakaart/koroonakaart#94]
Can you tell what is the source for hospitalizations?

I would like to generate a cumulative graph of hospitalizations (especially by county, better by age group).

**Comment by bmiis** [comment]
Copied From #87 PS.
_For the "PS", this data comes from Terviseamet's press releases, unfortunately not available via TEHIK right now._

**Comment by keeganmcbride** [comment]
Data just comes from press releases, by county data is not available, unfortunately. I hope TEHIK can try to do something about this in the future.
