### ISSUE TITLE
Country comparison

### ISSUE THREAD

**Issue by PierpaoloFerrante** [koroonakaart/koroonakaart#97]
An important problem with corona virus is the large number of mild cases that drives the virus to 'weak' people. It is crucial to find these hidden active cases for protecting weak people, but how many are they?
Italian data about COVID-19 seem to indicate that for every hospitalised case there are at least three active mild cases that should be put under quarantine, otherwise they could seriously spread the virus.
some reports on this way
https://www.linkedin.com/posts/pierpaolo-ferrante-05699077_covid-19-in-italy-03-21-2020-one-important-activity-6647184502655332352-Dqog
https://www.linkedin.com/posts/pierpaolo-ferrante-05699077_covid-19-in-italy-03-27-2020-an-important-activity-6649157951485419520-laEb
https://www.linkedin.com/posts/pierpaolo-ferrante-05699077_coronavirus-publichealth-healthcare-activity-6647932920474419200-BDAK

It would be usefull to provide number of hospitalized (standard and intensive care) patients but also people under quarantine day by day.

Italian data
.pdf at http://www.salute.gov.it/imgs/C_17_notizie_4403_0_file.pdf)
.csv at https://github.com/pcm-dpc/COVID-19/tree/master/dati-regioni

Would it be possibile to make available data such Italian ones?

Thank you for your time

**Comment by keeganmcbride** [comment]
Hi, unfortunately this data is not available yet and it  likely will not be in the near future. I will close for now.

**Comment by PierpaoloFerrante** [comment]
Thank you for your support.

Best regards

Il Mer 15 Apr 2020, 09:59 keeganmcbride <notifications@github.com> ha
scritto:
